version: '3'
services:
  internal:
    build:
      context: .

    entrypoint:
     - node
     - internal

    ports:
     - 3000

  external:
    build:
      context: .

    entrypoint:
     - node
     - external

    ports:
     - 80:3000
