version: '3'
services:
  internal:
    build:
      context: .

    entrypoint:
     - node
     - internal

    # Port will only be visible within docker
    ports:
     - 3000

  external:
    build:
      context: .

    entrypoint:
     - node
     - external

    # Port 80 is visible publicly
    ports:
     - 80:3000
